README.md
lang/README.en.md

Add SCP command in README.en.md

---

lang/README.en.md

Added SCP command for server to local copy

---

lang/README.en.md

Commands constants wrapped in braces

---

README.md
commands/SCP.md
commands/SSH.md
lang/README.hi.md

Removed multi language, restructuring of code

---

commands/DOCKER.md

Corrected typo: CONAINER -> CONTAINER

---

commands/mongo/mongo.md
commands/scp/scp.md

broken link in mongo and scp fixed

---

commands/docker/docker-create-db.md
commands/docker/docker-login.md
commands/docker/docker.md

Fixes #
[x] Add docker login command
[x] Add docker create db commands

Docker login to container and Docker create db commands added

---

commands/git/git.md

fixed broken link

---

README.md

fixed issue link for adding contributors

---

commands/docker/docker-cp.md

Container spelling fix

---

commands/docker/docker.md
commands/git/git.md

Listing sort

---

commands/docker/docker-container-commit.md

Added new docker commit command

add docker container commit command

---

README.md
commands/scp/scp.md
commands/zip/unzip-command.md
commands/zip/zip-command.md
commands/zip/zip.md

zip, unzip commands added

---

commands/docker/docker-logs-tail.md
commands/docker/docker.md

docker logs command added

---

README.md

Fixes #54
I have changed all the icons to point_right as suggested.
I hope it will be nice.

change README.md icons

---

commands/git/git-stash.md

Git stash command added

---

commands/git/git-stash-revert.md

Git stash revert added

---

commands/git/git-stash-list.md

Git stash list command added

---

commands/git/git-stash-file.md

Git stash file command added

---

commands/git/git.md

added all stash commands link to git.md

---

commands/docker/docker.md
commands/git/git.md
commands/mongo/mongo.md
commands/scp/scp.md
commands/ssh/ssh.md
commands/zip/zip.md

Fixes #66 
replaced title icon in readme inside every commands folder with the icon :point_left:

Replaced icons in command readmes

---

commands/python/python-build.md
commands/python/python-deploy-pypi.md
commands/python/python.md

python deployment commands added.

---

README.md

read me python link added

---

commands/git/git-rm-cached.md
commands/git/git.md

git rm cached command added

---

README.md
commands/heroku/heroku-ps.md
commands/heroku/heroku.md

Fixes #75 
1. Added heroku ps command with description and examples
2. Added Heroku in Readme file

Added heroku ps command

---

commands/git/git-reset.md
commands/git/git.md

Git reset command added

---

commands/docker/docker-load.md
commands/docker/readme.md

adds docker load command

---

commands/docker/docker-container-commit.md
commands/docker/docker-container-create.md
commands/docker/docker-container-list.md
commands/docker/docker-container-rm.md
commands/docker/docker-cp.md
commands/docker/docker-image-rm.md
commands/docker/docker-images-list.md
commands/docker/docker-load.md
commands/docker/readme.md

create container command, restructing and cleanup

---

commands/docker/docker-run.md
commands/docker/readme.md

Command to run docker container using an image id

Docker run command

---

commands/git/git-clone-repo.md
commands/git/git-commit.md
commands/git/git-name-email-config-check.md
commands/git/git-name-email-config.md
commands/git/git-stage.md
commands/git/git-status.md

git related commands, clone, commit, config, stage, status

---

commands/zip/unzip-command.md
commands/zip/zip-command-encryption.md
commands/zip/zip-command.md

adds related commands to all zip commands

---

commands/git/git-reset.md
commands/git/git-rm-cached.md
commands/git/git-stash-file.md
commands/git/git-stash-list.md
commands/git/git-stash-revert.md
commands/git/git-stash.md

Adds related commands to all git commands detail page

---

commands/npm/npm-init.md
commands/npm/npm-login.md
commands/npm/npm-publish.md

npm related commands

---

commands/git/git-clone-repo.md
commands/git/git-commit.md
commands/git/git-name-email-config-check.md
commands/git/git-name-email-config.md
commands/git/git-new-branch.md
commands/git/git-pull.md
commands/git/git-push.md
commands/git/git-reset.md
commands/git/git-rm-cached.md
commands/git/git-stage.md
commands/git/git-stash-file.md
commands/git/git-stash-list.md
commands/git/git-stash-revert.md
commands/git/git-stash.md
commands/git/git-status.md
commands/git/git-switch-branch.md

changes all h2 tags to h3 for git commands

---

README.md
commands/docker/docker-build-image-with-dockerfile.md
commands/docker/readme.md

adds docker build command

---

commands/mongo/mongo-dump-collection.md
commands/mongo/mongo-restore-collection.md

Adds mongo related commands

---

commands/scp/scp-local-to-server.md
commands/scp/scp-server-to-local.md

adds scp related command details

---

commands/python/python-build.md
commands/python/python-deploy-pypi.md

adds related commands for python

---

README.md
commands/docker/docker-save.md
commands/docker/readme.md

adds docker save iamge command

---

README.md
commands/git/git-commit-amend.md
commands/git/git-commit.md
commands/git/readme.md

git commit ammend commands added

---

README.md
commands/docker/docker-container-ip.md
commands/docker/readme.md

adds command for getting container ip in docker

---

commands/linux/tail-one-file.md

Broken link fix in tail-one-file

---

README.md
commands/linux/readme.md
commands/linux/search-application-process.md

Adds search application process grep command

---

.github/FUNDING.yml

adds sponsor details

---

README.md
commands/git/git-reflog.md
commands/git/readme.md

Add git reflog command and demo gif

---

README.md
commands/docker/docker-cp-from-container.md
commands/docker/docker-cp.md
commands/docker/readme.md

Add docker cp from container to host

---

README.md
commands/git/git-restore-branch.md
commands/git/readme.md

Add command to restore locally deleted branch

---

README.md
commands/tar/extract.md
commands/tar/readme.md

Add tar category and extract command usage

---

README.md
commands/docker/docker-container-ip.md
commands/docker/docker-inspect.md

Add docker inspect command

---

commands/docker/docker-load.md

Fix small link typo in the docker-load md

Fix typo in docker-load.md

---

README.md
commands/kafka/kafka.md
commands/kafka/readme.md

kafka: create topic

---

README.md

Make the titles sentence case

---

README.md
commands/linux/clear.md
commands/linux/readme.md

Add: Linux clear command

---

README.md

Fixes #196 
- Removed the sponsor badges `Buy Me a Coffee` and `Patron` from the readme
- Removed `Please consider donating, if you like my work` line from the readme

removed coffee & patron badges and donate line

---

README.md

Add center tag for header

---

.github/FUNDING.yml

removed .github directory

---

README.md

Remove contributors section from readme

---

README.md
commands/git/git-squash-merge-branch.md

Fixes #209
- Have only included git squash merge command in this PR

Add git squash merge command
